

import json
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Any

class HTMLReporter:
    """Generate beautiful HTML reports from test execution results"""
    
    def __init__(self, output_dir: str = "./outputs"):
        self.output_dir = Path(output_dir)
        self.reports_dir = self.output_dir / "reports"
        self.html_reports_dir = self.output_dir / "html_reports"
        self.screenshots_dir = self.output_dir / "screenshots"
        
        # Create HTML reports directory
        self.html_reports_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_html_report(self, json_report_path: str) -> str:
        """Generate HTML report from JSON report file"""
        with open(json_report_path, 'r') as f:
            report_data = json.load(f)
        
        html_content = self._create_html_report(report_data)
        
        test_id = report_data.get('test_id', 'unknown')
        html_filename = f"report_{test_id}.html"
        html_path = self.html_reports_dir / html_filename
        
        with open(html_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        print(f"✓ HTML report generated: {html_path}")
        return str(html_path)
    
    def generate_from_test_result(self, test_result: Dict[str, Any]) -> str:
        """Generate HTML report directly from test result dictionary"""
        html_content = self._create_html_report(test_result)
        
        test_id = test_result.get('test_id', datetime.now().strftime("%Y%m%d_%H%M%S"))
        html_filename = f"report_{test_id}.html"
        html_path = self.html_reports_dir / html_filename
        
        with open(html_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        print(f"✓ HTML report generated: {html_path}")
        return str(html_path)
    
    def _create_html_report(self, report_data: Dict[str, Any]) -> str:
        """Create HTML content from report data"""
        
        # Extract data
        test_id = report_data.get('test_id', 'N/A')
        success = report_data.get('success', False)
        message = report_data.get('message', 'No message')
        execution_time = report_data.get('execution_time', 0)
        target_url = report_data.get('target_url', 'N/A')
        timestamp = report_data.get('timestamp', 'N/A')
        screenshots = report_data.get('screenshots', [])
        errors = report_data.get('errors', [])
        logs = report_data.get('logs', [])
        
        # Status styling
        status_color = '#4CAF50' if success else '#f44336'
        status_text = '✅ PASSED' if success else '❌ FAILED'
        
        # Build screenshots HTML
        screenshots_html = self._build_screenshots_html(screenshots)
        
        # Build errors HTML
        errors_html = self._build_errors_html(errors)
        
        # Build logs HTML
        logs_html = self._build_logs_html(logs)
        
        # Complete HTML
        html = f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test Report - {test_id}</title>
    {self._get_css_styles(status_color)}
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🧪 Test Execution Report</h1>
            <div class="test-id">Test ID: {test_id}</div>
            <div class="status-badge">{status_text}</div>
        </div>
        
        <div class="summary">
            <div class="summary-item">
                <h3>Execution Time</h3>
                <div class="value">{execution_time:.2f}s</div>
            </div>
            <div class="summary-item">
                <h3>Target URL</h3>
                <div class="value" style="font-size: 16px; word-break: break-all;">{target_url}</div>
            </div>
            <div class="summary-item">
                <h3>Timestamp</h3>
                <div class="value" style="font-size: 14px;">{timestamp}</div>
            </div>
            <div class="summary-item">
                <h3>Screenshots</h3>
                <div class="value">{len(screenshots)}</div>
            </div>
        </div>
        
        <div class="section">
            <h2>💬 Message</h2>
            <div class="message-box">{message}</div>
        </div>
        
        {screenshots_html}
        {errors_html}
        {logs_html}
        
        <div class="footer">
            <p>Generated by E2E Testing Agent | {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
        </div>
    </div>
</body>
</html>'''
        
        return html
    
    def _build_screenshots_html(self, screenshots: List[str]) -> str:
        """Build HTML for screenshots section"""
        if not screenshots:
            return ''
        
        html = '<div class="section"><h2>📸 Screenshots</h2><div class="screenshots-grid">'
        for i, screenshot in enumerate(screenshots, 1):
            screenshot_name = Path(screenshot).name
            html += f'''
            <div class="screenshot-item">
                <h3>Screenshot {i}</h3>
                <img src="../screenshots/{screenshot_name}" alt="Screenshot {i}" onclick="window.open(this.src)">
                <p>{screenshot_name}</p>
            </div>
            '''
        html += '</div></div>'
        return html
    
    def _build_errors_html(self, errors: List[Dict]) -> str:
        """Build HTML for errors section"""
        if not errors:
            return ''
        
        html = '<div class="section errors-section"><h2>❌ Errors</h2>'
        for i, error in enumerate(errors, 1):
            error_type = error.get('type', 'Unknown')
            error_message = error.get('message', 'No message')
            html += f'''
            <div class="error-item">
                <strong>Error {i}: {error_type}</strong>
                <p>{error_message}</p>
            </div>
            '''
        html += '</div>'
        return html
    
    def _build_logs_html(self, logs: List[str]) -> str:
        """Build HTML for logs section"""
        if not logs:
            return ''
        
        html = '<div class="section"><h2>📝 Execution Logs</h2><div class="logs">'
        for log in logs[-20:]:  # Show last 20 logs
            html += f'<div class="log-entry">{log}</div>'
        html += '</div></div>'
        return html
    
    def _get_css_styles(self, status_color: str) -> str:
        """Return CSS styles for the HTML report"""
        return f'''
    <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            padding: 20px;
            min-height: 100vh;
        }}
        
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            border-radius: 15px;
            box-shadow: 0 10px 40px rgba(0,0,0,0.2);
            overflow: hidden;
        }}
        
        .header {{
            background: {status_color};
            color: white;
            padding: 40px;
            text-align: center;
        }}
        
        .header h1 {{
            font-size: 36px;
            margin-bottom: 15px;
        }}
        
        .header .test-id {{
            font-size: 14px;
            opacity: 0.9;
            margin-bottom: 20px;
        }}
        
        .status-badge {{
            display: inline-block;
            padding: 12px 30px;
            background: rgba(255,255,255,0.2);
            border-radius: 25px;
            font-size: 20px;
            font-weight: bold;
            margin-top: 10px;
        }}
        
        .summary {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 20px;
            padding: 30px;
            background: #f8f9fa;
        }}
        
        .summary-item {{
            background: white;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        
        .summary-item h3 {{
            color: #666;
            font-size: 14px;
            margin-bottom: 10px;
            text-transform: uppercase;
        }}
        
        .summary-item .value {{
            font-size: 24px;
            font-weight: bold;
            color: #333;
        }}
        
        .section {{
            padding: 30px;
            border-top: 1px solid #eee;
        }}
        
        .section h2 {{
            font-size: 24px;
            margin-bottom: 20px;
            color: #333;
        }}
        
        .message-box {{
            background: #e3f2fd;
            padding: 15px 20px;
            border-radius: 8px;
            border-left: 4px solid #2196F3;
        }}
        
        .screenshots-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
            gap: 20px;
        }}
        
        .screenshot-item {{
            background: #f5f5f5;
            padding: 15px;
            border-radius: 8px;
            text-align: center;
        }}
        
        .screenshot-item h3 {{
            color: #667eea;
            margin-bottom: 10px;
            font-size: 16px;
        }}
        
        .screenshot-item img {{
            max-width: 100%;
            border-radius: 5px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
            cursor: pointer;
            transition: transform 0.2s;
        }}
        
        .screenshot-item img:hover {{
            transform: scale(1.05);
        }}
        
        .screenshot-item p {{
            margin-top: 10px;
            font-size: 12px;
            color: #666;
            word-break: break-all;
        }}
        
        .errors-section {{
            background: #ffebee;
        }}
        
        .error-item {{
            background: white;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 10px;
            border-left: 4px solid #f44336;
        }}
        
        .error-item strong {{
            color: #c62828;
            display: block;
            margin-bottom: 8px;
        }}
        
        .error-item p {{
            color: #666;
        }}
        
        .logs {{
            background: #263238;
            padding: 20px;
            border-radius: 8px;
            max-height: 400px;
            overflow-y: auto;
        }}
        
        .log-entry {{
            color: #a5d6a7;
            font-family: 'Courier New', monospace;
            font-size: 13px;
            padding: 4px 0;
            border-bottom: 1px solid rgba(255,255,255,0.1);
        }}
        
        .log-entry:last-child {{
            border-bottom: none;
        }}
        
        .footer {{
            padding: 20px;
            text-align: center;
            background: #f8f9fa;
            color: #666;
            font-size: 14px;
        }}
    </style>
    '''
    
    def list_html_reports(self) -> List[Dict[str, str]]:
        """List all generated HTML reports"""
        reports = []
        for html_file in sorted(self.html_reports_dir.glob("report_*.html"), reverse=True):
            reports.append({
                "filename": html_file.name,
                "path": str(html_file),
                "created": datetime.fromtimestamp(html_file.stat().st_mtime).strftime("%Y-%m-%d %H:%M:%S")
            })
        return reports


# Example usage
if __name__ == "__main__":
    # Test the reporter
    reporter = HTMLReporter()
    
    # Sample test result
    sample_result = {
        "test_id": "20250106_150000",
        "success": True,
        "message": "Test completed successfully",
        "execution_time": 3.45,
        "target_url": "https://example.com",
        "timestamp": "2026-01-06T15:00:00",
        "screenshots": ["screenshot1.png", "screenshot2.png"],
        "errors": [],
        "logs": ["Starting test...", "Navigating to URL...", "Test completed"]
    }
    
    # Generate HTML report
    html_path = reporter.generate_from_test_result(sample_result)
    print(f"HTML report created at: {html_path}")